name: Main PR Pipeline

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: self-hosted
    container:
      image: alpine:3.15
    steps:
      - name: Define proper Checkout REF
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}})"
        id: extract_ref
      - uses: actions/checkout@v2
        with:
          ref: "${{ steps.extract_ref.outputs.ref }}"
      - uses: ./
      - shell: sh
        run: echo "Hello World"
      - name: show file system
        shell: sh
        run: ls -la
      - name: show file system
        shell: sh
        run: ls -la
