name: Main PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.15
    steps:
      - name: Define proper Checkout REF
        shell: sh
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}})"
        id: extract_ref
      - uses: actions/checkout@v2
        with:
          ref: "${{ steps.extract_ref.outputs.ref }}"
      - name: Test local action
        uses: ./
      - run: |
          if [ -z "$(ls -A .)" ]; then
            exit 0
          else
            echo "Folder is not empty"
            ls -A .
            exit 1
          fi
      - uses: actions/checkout@v2
        with:
          ref: "${{ steps.extract_ref.outputs.ref }}"
